### ISSUE TITLE
cy_renumerate.sh not found

### ISSUE THREAD

**Issue by AleXoundOS** [hmaarrfk/libcyusb#2]
The `install.sh` script references `cy_renumerate.sh` file in several places. However I couldn't find it before nor after the build. Is `install.sh` intended to work properly or was brought into repository unintentionally?

**Comment by hmaarrfk** [comment]
find it in their source from their website i guess. PR welcome to bring it in here.

**Comment by AleXoundOS** [comment]
I thought it can be essential for the library to work. Is the library ready to work with ezusb on modern Linux without special setup procedure with adding custom udev rules (`install.sh` should do this)?

**Comment by hmaarrfk** [comment]
feel free to make whatever pr you want. i just made  a dump of the code here

**Comment by AleXoundOS** [comment]
After writing some code that does something practical with EZ-USB, I've also come to the same conclusion as you about doubtful usefulness of the Cypress USB Library for Linux. At least for my tasks, the [usb](http://basvandijk.github.io/usb/) library makes the job done with `libusb` under the hood.
No need for configuration files, enumerate scripts or whatever.

So, I close the issue.

**Comment by hmaarrfk** [comment]
:D glad things are working for you!
