### ISSUE TITLE
Configure_file Problem configuring file

### ISSUE THREAD

**Issue by Survial53** [hmaarrfk/libcyusb#4]
I get errorr when try build project with cmake:

```
CMake Error at CMakeLists.txt:38 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!
```

Can you add cyusbConfig.cmake file which copying at line 38 (CMakeLists.txt):

`configure_file(cyusbConfig.cmake "${CMAKE_CURRENT_BINARY_DIR}/cyusbConfig.cmake" COPYONLY)
`

**Comment by hmaarrfk** [comment]
I'm not sure it was ever there in the zip I got. I think Cypress is maintaining a zip somewhere. If you wanted to make a PR adding the missing file then I could accept it in.

As I've mentionned before, this is only of use when trying to find out what libusb calls to make.

**Comment by hmaarrfk** [comment]
Mentionned in other issue threads, not to you.
